### ISSUE TITLE
Retrieve job_id from salesforce-bulk create_job

### ISSUE THREAD

**Issue by khgould** [heroku/salesforce-bulk#102]
hi folks, 
How can we return the job_id for each job created using the create_job method? I know there is another method to get the job_status... but how about the id?

**Comment by alouie-sfdc** [comment]
Hi @khgould, the `create_job` method returns the id of the job that gets created: https://github.com/heroku/salesforce-bulk/blob/main/salesforce_bulk/salesforce_bulk.py#L215

You can see some examples in the tests, such as: https://github.com/heroku/salesforce-bulk/blob/main/salesforce_bulk/tests/test_salesforce_bulk.py#L350

Does that answer your question, or were you asking about something else?

**Comment by khgould** [comment]
Thanks!
Silly me.
