### ISSUE TITLE
Calling bulk_delete() results in error in get_batch_results()

### ISSUE THREAD

**Issue by aschriner** [heroku/salesforce-bulk#11]
Error is
`get_batch_results() got an unexpected keyword argument 'callback'`

The function get_batch_results does not take a 'callback' argument according to its definition in line 399, yet is called in line 284 with 'callback' argument

**Comment by spgoofyft** [comment]
You can use the post_bulk_batch() method with a Delete job.

**Comment by YonatanKiron** [comment]
Is this error going to be solved?

**Comment by lambacck** [comment]
Fixed in #32
