### ISSUE TITLE
Add httplib2 to setup.py

### ISSUE THREAD

**Issue by travistruett** [heroku/salesforce-bulk#2]
Trying to install salesforce-bulk by running requirements.txt and it's erroring because it cannot find httplib2. I'm currently having to manually install httplib2 separately for everything to work because simply adding it to requirements.txt doesn't seem to do the trick. 

I might be missing something, but why is this library not added to salesforce-bulk's setup.py file?

Thanks,
Travis

**Comment by lambacck** [comment]
Fixed in #3
