### ISSUE TITLE
https://pypi.python.org/pypi/salesforce-bulk baldy formatted

### ISSUE THREAD

**Issue by zopyx** [heroku/salesforce-bulk#25]
Please fix the layout/markup of the documentation of this release. 
It hurts my eyes seeing such brown bag releases in 2015.

**Comment by Jeremydavisvt** [comment]
Could you be more specific?

**Comment by zopyx** [comment]
are you joking???

**Comment by Jeremydavisvt** [comment]
Ah, I thought you were referring to the readme. Yeah, it could use some work. I'm not sure how maintained this project is but, the documentation in github is effectively the same, just better formatted.

**Comment by lambacck** [comment]
This was fixed in #54
