### ISSUE TITLE
support for Python 3

### ISSUE THREAD

**Issue by x110dc** [heroku/salesforce-bulk#27]
```
Traceback (most recent call last):
  File "reconcile.py", line 5, in <module>
    from salesforce_bulk import SalesforceBulk
  File "/usr/local/lib/python3.4/dist-packages/salesforce_bulk/__init__.py", line 1, in <module>
    from salesforce_bulk import SalesforceBulk
ImportError: cannot import name 'SalesforceBulk'
```

**Comment by subject117** [comment]
I tried to port this library to Python 3 and failed.

The first step is to use 2to3, which was fairly simple. It changed some of the imports and a few other things.

The first non-obvious problem was when I tried running it I would get a byte/str type error while creating a job. I realized I had to change the StringIO stuff to look like this:

```
        buf = io.BytesIO()
        tree = ET.ElementTree(root)
        tree.write(buf, encoding="UTF-8")
        return buf.getvalue().decode('UTF-8')
```

Did that in a few places. I still couldn't create a job though. I was creating the SalesforceBulk object by passing in a sessionId and kept getting a session id invalid error. It was the same sessionId I would pass in when running in Python 2.7. I don't get it. Somehow it is not passing the sessionId correctly in the header?

This does need to be ported to Python3 but I can't spend more time on it. Hope the above info helps the next person to try.
