### ISSUE TITLE
Make the Batch ContentType a parameter

### ISSUE THREAD

**Issue by godd9170** [heroku/salesforce-bulk#29]
I want to post JSON batches, however the `post_bulk_batch` function seems to hardcode in "text/csv" as the ContentType [here](https://github.com/heroku/salesforce-bulk/blob/master/salesforce_bulk/salesforce_bulk.py#L293).

Is there a way to 'batchify' json posts?

**Comment by godd9170** [comment]
Arg.. It seems that Json isn't yet supported. See the Considerations at the bottom of this [doc](https://developer.salesforce.com/docs/atlas.en-us.api_asynch.meta/api_asynch/asynch_api_mapping.htm)

**Comment by tomaszb** [comment]
Agreed, I have to do a zip/csv request and had to overwrite the class.
