### ISSUE TITLE
getting the Null byte exception while running query

### ISSUE THREAD

**Issue by santhoshch** [heroku/salesforce-bulk#35]
recs = [r for r in records]
File "/usr/local/lib/python2.7/dist-packages/salesforce_bulk/salesforce_bulk.py", line 419, in get_batch_results
for i, line in enumerate(iterator):
Error: line contains NULL byte

**Comment by JackaDu** [comment]
same issue

**Comment by santhoshch** [comment]
in salesforce_bulk.py i have to added 472 and 512 lines with 
iterator = csv.reader((x.replace('\0', '') for x in resp.iter_lines()), ...)
to make it work for me

**Comment by lambacck** [comment]
Fixed in #40
