### ISSUE TITLE
Bulk.insert Error

### ISSUE THREAD

**Issue by synaqvi** [heroku/salesforce-bulk#47]
Hi

I am testing this with 100 Account rows and a batch size equals to 200. Everything is working fine from login to upload but during the process, it is continuously showing me following error:

`salesforce-processing/Bulk.insert: Failure in processing file: Account.csv on pod: test-dev. Details: SFHelper.status: Call was successful, but some rows failed. Details: [{"batchId": "Id", "error": "Error"}]`

Even after getting this error every time I run, all the records get uploaded to Salesforce without any issues.

Can anyone help me out please why I am getting this error over and over again whereas, there is nothing wrong with the records uploaded to Salesforce?

**Comment by lambacck** [comment]
are you using the version off pypi or version 2.0 preview as exists in the master branch? You can install the current 2.0 preview by following the instructions in this comment: https://github.com/heroku/salesforce-bulk/issues/44#issuecomment-315139386

**Comment by synaqvi** [comment]
Followed the instruction provided by you but still getting the same error.

**Comment by lambacck** [comment]
There may be more details in the job status doc. You may also want to look at the job details in the salesforce bulk interface under setup.

**Comment by lambacck** [comment]
There are insufficient details here to debug the issue. Please re-open if you have more details.
