### ISSUE TITLE
is_batch_done() takes exactly 3 arguments (2 given)

### ISSUE THREAD

**Issue by mastersilv3r** [heroku/salesforce-bulk#52]
Python 2.7

`from salesforce_bulk import SalesforceBulk
import json
             
bulk = SalesforceBulk(sessionId='', host='')

job = bulk.create_query_job("Contact", contentType='CSV')
batch = bulk.query(job, "select Id,LastName from Contact")
bulk.close_job(job)                 
while not bulk.is_batch_done(batch):
    sleep(10)
                                                                       
for result in bulk.get_all_results_for_query_batch(batch):             
    result = json.load(IteratorBytesIO(result))                        
    for row in result:                                                 
        print row # dictionary rows`

**Comment by lambacck** [comment]
Are you using the version from pypi or from master?

**Comment by mastersilv3r** [comment]
pypi

**Comment by lambacck** [comment]
The docs here are out of date for that version. You can install the latest version by using:
```
pip install 'https://github.com/heroku/salesforce-bulk/archive/v2.0.0dev6.zip#egg=salesforce-bulk==2.0.0dev6'
```
or adding 
```
https://github.com/heroku/salesforce-bulk/archive/v2.0.0dev6.zip#egg=salesforce-bulk==2.0.0dev6
```
to your requirements.txt file. I'm hoping to do a release to pypi soon.

**Comment by lambacck** [comment]
Updated install docs can be found in #53

**Comment by mastersilv3r** [comment]
Thank you!
