### ISSUE TITLE
PyPi Package is not up to date

### ISSUE THREAD

**Issue by brosenqui** [heroku/salesforce-bulk#68]
@lambacck
 
 I've been trying to use the salesforce-bulkipy library but have only run into errors when running it under a 3.5 environment. I cant create issues under the project directly so im doing it here

I've checked out the source that gets pulled into my environment from the pip install command but it is using different source from what's specified here. Specifically, it's missing all the python 3.x support it seems.

See Python [logs](https://pastebin.com/s7ycS6Cy) for details

If i execute the same script under a 2.7 environment, it works. I stumbled onto it when i had to make some of the same changes that were performed on the real master branch and noticed the versions were different. I was thinking of making a PR for them anyways but it seems i should have gotten the changes in the first place.

**Comment by lambacck** [comment]
https://pypi.org/project/salesforce-bulk/ is version 2.1.0 which is the current version in git here. Based on your log you are specifying salesforce-bulkipy==1.0 which is a different forked project.
