### ISSUE TITLE
Deprecate in favour of simple-salesforce

### ISSUE THREAD

**Issue by kokes** [heroku/salesforce-bulk#79]
Hey!
I remember using salesforce-bulk way back in the day, it was great, but it doesn't seem that updated anymore. We've been using [simple-salesforce](https://github.com/simple-salesforce/simple-salesforce) in production for a number of years and it's been very solid and has continued support (1.0 is planned - https://github.com/simple-salesforce/simple-salesforce/pull/364). Also, it goes beyond just bulk (it does support it - https://github.com/simple-salesforce/simple-salesforce/commit/e9433e64cc3eef0c7a177aee1d8958a1c324f39d), it has a lot of SFDC introspection, non-bulk APIs etc.

Do you think that for the sake of consolidation in this space, you might consider archiving this in favour of simple-salesforce? Or, if not, somehow describe this library's future in the docs, so that it's clearer to its users?

cc @lambacck

**Comment by lambacck** [comment]
simple-salesforce at this time supports a subset of the Salesforce Bulk API. In particular it only supports JSON payloads. salesforce-bulk supports more of the Bulk API options including configuration of PK Chunking headers. While simple-salesforce might be fine for some bulk API use cases, advanced usage of the Bulk API is better supported by salesforce-bulk at this time.
