### ISSUE TITLE
Logger errors when getting batch results

### ISSUE THREAD

**Issue by ahmedtalhakhan** [heroku/salesforce-bulk#8]
The following lines in get_batch_result_iter are not correct and through exception

`logger("Bulk batch %s processed %d records" %
                       (batch_id, status['numberRecordsProcessed']))`

`logger("Bulk batch %s had %d failed records" %
                           (batch_id, failed))`

Two problems here
1. `logger` should be `logger.debug()`
2. `%d` directive is incorrect as the status contains these values as strings

**Comment by spgoofyft** [comment]
import logging

logging.basicConfig(level=logging.DEBUG)
results = bulk.get_batch_result_iter(job_id=job,batch_id=batch,parse_csv=True, logger=logging.debug)

**Comment by lambacck** [comment]
This logging is now gone as of #40
