### ISSUE TITLE
Salesforcelogin() got an unexpected keyword argument ‘sandbox’

### ISSUE THREAD

**Issue by GilbertLittle** [heroku/salesforce-bulk#80]
salesforce-bulk imports the salesforce-simple package for logging in to Salesforce.
It uses the SalesforceLogic class. salesforce-simple has been updated to version 1.0.0. This upgrade removes the sandbox parameter from the SalesforceLogin constructor.

![image](https://user-images.githubusercontent.com/36719604/77261749-83ea5980-6cdc-11ea-9d26-7fb36a36a9ca.png)

![image](https://user-images.githubusercontent.com/36719604/77261762-9fedfb00-6cdc-11ea-9ed4-b21f69b78cb9.png)

![image](https://user-images.githubusercontent.com/36719604/77261801-f52a0c80-6cdc-11ea-9c01-df2ed2746feb.png)

**Comment by naman-ratehub** [comment]
@GilbertLittle I'm getting the same error. Were you able to resolve it?

**Comment by ivanvenosdel** [comment]
Going forward, since simple-salesforce follows semantic versioning I think it would be a good idea to use a major version range for that dependency in the setup.py.

https://packaging.python.org/discussions/install-requires-vs-requirements/#id5
