### ISSUE TITLE
Need a new version which includes the simple-salesforce version bump fixes 

### ISSUE THREAD

**Issue by sumanth232** [heroku/salesforce-bulk#87]
The current version v2.1.0 is unusable due to its unpinned dependancy (simple-salesforce>0.69).
'pip install salesforce-bulk' downloads the latest version of simple-salesforce (1.10.1) which is not compatible with v2.1.0

A new release is needed to include the fixes made in https://github.com/heroku/salesforce-bulk/pull/86

**Comment by lambacck** [comment]
Yes a new release needs to be made but you don't have to wait for me to release it to use the new version. run `pip install https://github.com/heroku/salesforce-bulk/archive/f5db48284fed4e516e69cccdc991df57dd00a6c8.zip#egg=salesforce-bulk==2.2.0rc1"` to get it installed or add `https://github.com/heroku/salesforce-bulk/archive/f5db48284fed4e516e69cccdc991df57dd00a6c8.zip#egg=salesforce-bulk==2.2.0rc1` to your requirements.txt file.

**Comment by sumanth232** [comment]
This worked.
Thanks 😊
