### ISSUE TITLE
Documentation example does not work

### ISSUE THREAD

**Issue by ahmedtalhakhan** [heroku/salesforce-bulk#9]
Documentation example talks about using the function `get_batch_result_iter`
`
for row in bulk.get_batch_result_iter(job, batch, parse_csv=True):
    print row   #row is a dic
`

This is not correct. This function is not even getting the correct data. Instead of going to
something like
`https://ap1.salesforce.com/services/async/29.0/job/75090000001HbevAAC/batch/751900000028eiqAAA/result/752900000009oag`

Its is trying to get 
`https://ap1.salesforce.com/services/async/29.0/job/75090000001HbevAAC/batch/751900000028eiqAAA/result/`

which is incorrect.

**Comment by Vishalashah** [comment]
Did anyone fix this and create a new repo? Or is anyone open to take contributions?

**Comment by lambacck** [comment]
Fixed as of #40
