### ISSUE TITLE
Package at pypi claims to be v2.1.0 but it is older

### ISSUE THREAD

**Issue by atsgeiger** [heroku/salesforce-bulk#90]
The code appears to be before the fix for [sandbox param](https://github.com/heroku/salesforce-bulk/issues/80) in the underlying login/auth code.

When installing the pypi version, you get an older version which does not work with the packaged simple-salesforce package.

**Comment by rwhaling** [comment]
I'm seeing this as well - according to PyPI, the 2.1.0 release is from Feb. 2018?  Is there anywhere I can get an up-to-date version?

https://pypi.org/project/salesforce-bulk/2.1.0/#history

**Comment by ivanvenosdel** [comment]
As far as I can tell, the project just hasn't bumped a new version or released a new PyPI version yet. 

Here is a work around for getting the sandbox param fix. Note that this is a reusable concept for any project with unreleased code.:

Pipfile entry
```
salesforce-bulk = {git = "https://github.com/heroku/salesforce-bulk.git", editable = true, ref = "f5db48284fed4e516e69cccdc991df57dd00a6c8"}
```

One can google around for the pip/requirements.txt equivalent.

**Comment by jhole89** [comment]
My team is also getting hit by this, is this project being actively maintained?

**Comment by lambacck** [comment]
Version 2.2.0 was published and has resolved the compatibility with simple salesforce and sandboxes.
